//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string ScriptTitle { get; set; }
        public string Amount { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<System.DateTime> TransactionTime { get; set; }
    }
}
